on:
  release:
    types: [published]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    name: test-workflow-cloud-pw
    steps:
      - name: run-workflow
        id: run-cloud-pw
        uses: parallelworks/test-workflow-action@v5
        with:
          pw-user-host: 'cloud.parallel.works'
          pw-api-key: ${{ secrets.PW_API_KEY }}
          pw-user: 'sfgary'
          resource-pool-names: 'cloud'
          workflow-name: 'ssh_bash_demo'
          workflow-parameters: '{"commands|whost": "cloud.clusters.pw", "commands|rundir": "/var", "commands|runcmd": "ls -a -l -h", "commands|spaces_in_runcmd": "True", "commands|sleep_time": "10", "commands|head_or_worker": "False"}'
